### ISSUE TITLE
NullPointerException in BaseMpscLinkedArrayQueue

### ISSUE THREAD

**Issue by alexandru** [JCTools/JCTools#161]
While testing (with JCTools 2.0.1 and Java 8), I bumped into this ugly error:

```
#
[thread 30219 also had an error]# A fatal error has been detected by the Java Runtime Environment:

#
#  SIGSEGV (0xb) at pc=0x00000001111866a8, pid=66522, tid=0x0000000000007f07
#
# JRE version: Java(TM) SE Runtime Environment (8.0_112-b16) (build 1.8.0_112-b16)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.112-b16 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# J 18463 C2 monix.reactive.observers.buffers.ConcurrentQueue$FromMessagePassingQueue.poll()Ljava/lang/Object; (10 bytes) @ 0x00000001111866a8 [0x0000000111186640+0x68]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
[thread 5135 also had an error]
java.lang.NullPointerException
	at org.jctools.queues.BaseMpscLinkedArrayQueue.newBufferAndOffset(BaseMpscLinkedArrayQueue.java:320)
	at org.jctools.queues.BaseMpscLinkedArrayQueue.newBufferPoll(BaseMpscLinkedArrayQueue.java:299)
	at org.jctools.queues.BaseMpscLinkedArrayQueue.relaxedPoll(BaseMpscLinkedArrayQueue.java:429)
	at monix.reactive.observers.buffers.ConcurrentQueue$FromMessagePassingQueue.poll(ConcurrentQueue.scala:108)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.monix$reactive$observers$buffers$AbstractSimpleBufferedSubscriber$$anon$$fastLoop(SimpleBufferedSubscriber.scala:196)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.run(SimpleBufferedSubscriber.scala:134)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at # An error report file with more information is saved as:
# /Users/alex/Projects/monix/monix/hs_err_pid66522.log
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.NullPointerException
	at org.jctools.queues.BaseMpscLinkedArrayQueue.newBufferAndOffset(BaseMpscLinkedArrayQueue.java:320)
	at org.jctools.queues.BaseMpscLinkedArrayQueue.newBufferPoll(BaseMpscLinkedArrayQueue.java:299)
	at org.jctools.queues.BaseMpscLinkedArrayQueue.relaxedPoll(BaseMpscLinkedArrayQueue.java:429)
	at monix.reactive.observers.buffers.ConcurrentQueue$FromMessagePassingQueue.poll(ConcurrentQueue.scala:108)
	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.monix$reactive$observers$buffers$AbstractSimpleBufferedSubscriber$$anon$$fastLoop(SimpleBufferedSubscriber.scala:196)
[thread 26655 also had an error]	at monix.reactive.observers.buffers.AbstractSimpleBufferedSubscriber$$anon$1.run(SimpleBufferedSubscriber.scala:134)

	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Looking at the code, the NPE happened in this function:

```java
    private long newBufferAndOffset(E[] nextBuffer, final long index) {
        consumerBuffer = nextBuffer;
        consumerMask = (nextBuffer.length - 2) << 1; // <<< HERE!
        final long offsetInNew = modifiedCalcElementOffset(index, consumerMask);
        return offsetInNew;
    }
```

The error described at my `SimpleBufferedSubscriber.scala:134` is basically a result of a `queue.relaxedPoll()`.

This error is not easily reproducible and I don't understand the conditions that made it happen. But seeing it is freaking scary and I'd like to know if you've seen this before, what to do, etc.

**Comment by alexandru** [comment]
This might have happened in combination with an `OutOfMemoryException` that's not shown in that output, but I'm not sure. Trying to figure out if this was my fault or not.

**Comment by nitsanw** [comment]
An OOM is a bit of a bugger of a state to be in, so if it only happens in conjuction this is hard to reason about.
The implication here is that nextBuffer is null, which in turn mean that JUMP is visible before the next array (not the case AFAICT, see here: https://github.com/JCTools/JCTools/blob/cd5fec0a096b4b9a5d4589f32991f36663395733/jctools-core/src/main/java/org/jctools/queues/BaseMpscLinkedArrayQueue.java#L517), OR perhaps that you have 2 consumer threads?

**Comment by nitsanw** [comment]
What is causing the core dump?

**Comment by alexandru** [comment]
> OR perhaps that you have 2 consumer threads?

Ah, managing that consumer run-loop is hard, this might be a possibility.

Experienced some concurrency issues which might have yielded more than 1 consumer loop, managed to get it into a state where problems are no longer visible.

**Comment by nitsanw** [comment]
Closing, please reopen if you have evidence of issue.
