### ISSUE TITLE
Non-linearizable return value of put operation in NonBlockingHashMapLong

### ISSUE THREAD

**Issue by alefedor** [JCTools/JCTools#319]
There is a bug in jctools 3.1 that results in `NonBlockingHashMapLong.put` returning not the previous value, but the next one added in a concurrent thread.

The bug can be reproduced with [Lincheck](https://github.com/Kotlin/kotlinx-lincheck).
The scenario with incorrect results has two parallel threads with one operation each, and one operation after the threads are finished:
```
Parallel part:
| put(5, -2): null | put(5, -8): -2 |
Post part:
[get(5): -2]
```
If `put(5, -8)` returned `-2`, then the result of the next `get` should have been `-8`.

There was the same bug in jctools 2.1 for `NonBlockingHashMap`, which seem to be fixed. 

In case the reasons of the bug differ from `NonBlockingHashMap`, I also attach the trace with only two context switches that leads to non-linearizable results (yet to be released feature in Lincheck).
```
= Parallel part execution: =
|                      | put(5, -8)                                                                                            |
|                      |   _chm.READ: @313a67ba at NonBlockingHashMapLong.putIfMatch(NonBlockingHashMapLong.java:316)          |
|                      |   READ: null at NonBlockingHashMapLong$CHM.putIfMatch(NonBlockingHashMapLong.java:559)                |
|                      |   switch                                                                                              |
| put(5, -2): null     |                                                                                                       |
|   thread is finished |                                                                                                       |
|                      |   READ: null at NonBlockingHashMapLong$CHM.putIfMatch(NonBlockingHashMapLong.java:560)                |
|                      |   CAS_val(5,null,-8): false at NonBlockingHashMapLong$CHM.putIfMatch(NonBlockingHashMapLong.java:641) |
|                      |   READ: null at NonBlockingHashMapLong$CHM.putIfMatch(NonBlockingHashMapLong.java:651)                |
|                      |   result: -2                                                                                          |
|                      |   thread is finished                                                                                  |
```

**Comment by nitsanw** [comment]
Hi! Thanks for reporting! This looks like a useful test/tool, could you PR a working setup so we can add it to the release/build process?

**Comment by alefedor** [comment]
@nitsanw 
Hi! We are about to release a new testing mode for Lincheck that can much more than just stress testing.
I'll make a PR after we finish the release.

**Comment by nitsanw** [comment]
@alefedor that sounds awesome! thanks!

**Comment by alefedor** [comment]
@nitsanw 
Hi! The PR #328 is ready, though it took longer than expected, sorry.

**Comment by franz1981** [comment]
@alefedor thanks for this, it sounds really useful! Do you think it could worth to do it for queues?

**Comment by alefedor** [comment]
@franz1981 
I think it could be worth doing, because current queue tests seem to check some cases of linearizability, such as `testPeekAfterIsEmpty`, but it will be simpler and more effective to test linearizability in general with LinCheck.
LinCheck can even test single producer or single consumer queues by defining [non-parallel operation groups](https://github.com/Kotlin/kotlinx-lincheck#operation-groups).
The only problem I can think of is that it is not easy to test relaxed semantics, for example, when `relaxedPoll` can return `null` for not empty queue, so only regular versions of queue operation can be tested.

**Comment by franz1981** [comment]
Thanks @alefedor , having some robust check (and easier debugging path) for concurrent data-structures has a great value: I'm going to play a bit trying to replace some of our tests with it, but feel free to do it if you like, PRs are welcome :)
Thanks already for this great addition :+1:

**Comment by nitsanw** [comment]
For navigation purposes: "There was the same bug in jctools 2.1 for NonBlockingHashMap, which seem to be fixed." that was #205

**Comment by nitsanw** [comment]
Fixed
